/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_oxygen_inputfixosx_InputFix__ */

#ifndef _Included_org_oxygen_inputfixosx_InputFix__
#define _Included_org_oxygen_inputfixosx_InputFix__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_oxygen_inputfixosx_InputFix__
 * Method:    patchKeyEvents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_oxygen_inputfixosx_InputFix_00024_patchKeyEvents
  (JNIEnv *, jobject);

/*
 * Class:     org_oxygen_inputfixosx_InputFix__
 * Method:    enableInputMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_oxygen_inputfixosx_InputFix_00024_enableInputMethod
  (JNIEnv *, jobject);

/*
 * Class:     org_oxygen_inputfixosx_InputFix__
 * Method:    disableInputMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_oxygen_inputfixosx_InputFix_00024_disableInputMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
